"""
Knowledge base seed data: 55+ common Windows error patterns.
Categories: BSOD, Service, Network, Hardware, Active Directory, Office, Disk, Driver, Security, Performance
"""

KB_ENTRIES = [
    # ============================================================
    # BSOD (Blue Screen of Death) — 8 entries
    # ============================================================
    {
        "category": "BSOD",
        "subcategory": "Memory",
        "error_code": "0x0000007E",
        "error_pattern": r"(?i)(SYSTEM_THREAD_EXCEPTION_NOT_HANDLED|0x0000007E)",
        "title": "BSOD: SYSTEM_THREAD_EXCEPTION_NOT_HANDLED",
        "description": "Blue screen caused by a driver or system thread raising an unhandled exception.",
        "symptoms": "Machine crashes with blue screen showing STOP 0x7E. May occur on boot or during specific hardware use.",
        "root_cause": "Faulty or incompatible driver, corrupted system file, or failing RAM.",
        "remediation_steps": "1. Boot into Safe Mode.\n2. Run 'sfc /scannow' to check system files.\n3. Update or roll back the driver listed in the crash dump.\n4. Run Windows Memory Diagnostic.\n5. Check for Windows updates.",
        "remediation_script": "fix_bsod_general.ps1",
        "severity": "critical",
        "confidence": 0.85,
        "tags": "bsod,driver,crash,blue screen,memory",
    },
    {
        "category": "BSOD",
        "subcategory": "IRQ",
        "error_code": "0x0000000A",
        "error_pattern": r"(?i)(IRQL_NOT_LESS_OR_EQUAL|0x0000000A)",
        "title": "BSOD: IRQL_NOT_LESS_OR_EQUAL",
        "description": "Blue screen caused by a driver accessing paged memory at an invalid IRQL.",
        "symptoms": "System crashes with STOP 0x0A, often after installing new hardware or drivers.",
        "root_cause": "Driver bug, incompatible hardware, or corrupted system memory.",
        "remediation_steps": "1. Identify the faulting driver from the minidump.\n2. Update or uninstall the driver.\n3. Run 'verifier /standard /all' to enable Driver Verifier.\n4. Test RAM with Windows Memory Diagnostic.\n5. Check for BIOS/firmware updates.",
        "remediation_script": "fix_bsod_general.ps1",
        "severity": "critical",
        "confidence": 0.80,
        "tags": "bsod,irql,driver,hardware",
    },
    {
        "category": "BSOD",
        "subcategory": "Disk",
        "error_code": "0x00000077",
        "error_pattern": r"(?i)(KERNEL_STACK_INPAGE_ERROR|0x00000077)",
        "title": "BSOD: KERNEL_STACK_INPAGE_ERROR",
        "description": "Could not read a page of kernel data from the paging file.",
        "symptoms": "System crashes with STOP 0x77, may have slow disk performance before crash.",
        "root_cause": "Bad sectors on disk, failing HDD/SSD, corrupt paging file, or faulty SATA cable.",
        "remediation_steps": "1. Run 'chkdsk C: /f /r' in elevated cmd.\n2. Check SMART status of the drive.\n3. Delete and recreate the paging file.\n4. Replace SATA cable if applicable.\n5. Consider disk replacement if SMART reports errors.",
        "remediation_script": "fix_disk_check.ps1",
        "severity": "critical",
        "confidence": 0.82,
        "tags": "bsod,disk,paging,hdd,ssd",
    },
    {
        "category": "BSOD",
        "subcategory": "Memory",
        "error_code": "0x00000050",
        "error_pattern": r"(?i)(PAGE_FAULT_IN_NONPAGED_AREA|0x00000050)",
        "title": "BSOD: PAGE_FAULT_IN_NONPAGED_AREA",
        "description": "System tried to access invalid memory that should always be resident.",
        "symptoms": "BSOD with STOP 0x50, often random or during heavy workloads.",
        "root_cause": "Faulty RAM, buggy driver, or antivirus software conflict.",
        "remediation_steps": "1. Run Windows Memory Diagnostic (mdsched.exe).\n2. Disable recently installed antivirus.\n3. Update all drivers.\n4. Run 'sfc /scannow'.\n5. Test each RAM stick individually.",
        "remediation_script": "fix_bsod_general.ps1",
        "severity": "critical",
        "confidence": 0.78,
        "tags": "bsod,memory,ram,page fault",
    },
    {
        "category": "BSOD",
        "subcategory": "Storage",
        "error_code": "0x0000007A",
        "error_pattern": r"(?i)(KERNEL_DATA_INPAGE_ERROR|0x0000007A)",
        "title": "BSOD: KERNEL_DATA_INPAGE_ERROR",
        "description": "Requested page of kernel data could not be read into memory.",
        "symptoms": "BSOD with STOP 0x7A, system may exhibit sluggish I/O before crash.",
        "root_cause": "Disk drive failure, bad sectors, loose cabling, virus infection.",
        "remediation_steps": "1. Run 'chkdsk C: /f /r'.\n2. Check disk SMART health.\n3. Scan for malware.\n4. Check/replace SATA cables.\n5. Replace drive if failing.",
        "remediation_script": "fix_disk_check.ps1",
        "severity": "critical",
        "confidence": 0.80,
        "tags": "bsod,disk,kernel,storage",
    },
    {
        "category": "BSOD",
        "subcategory": "Driver",
        "error_code": "0x000000D1",
        "error_pattern": r"(?i)(DRIVER_IRQL_NOT_LESS_OR_EQUAL|0x000000D1)",
        "title": "BSOD: DRIVER_IRQL_NOT_LESS_OR_EQUAL",
        "description": "A driver accessed paged memory using an invalid address while at a raised IRQL.",
        "symptoms": "BSOD mentioning a specific .sys file. Common with network and GPU drivers.",
        "root_cause": "Buggy or outdated driver, commonly network adapters or GPU drivers.",
        "remediation_steps": "1. Note the .sys file from the BSOD.\n2. Identify and update the corresponding driver.\n3. Roll back if update does not help.\n4. Uninstall the device and let Windows reinstall it.\n5. Check manufacturer site for latest driver.",
        "remediation_script": "fix_bsod_general.ps1",
        "severity": "critical",
        "confidence": 0.85,
        "tags": "bsod,driver,irql,network,gpu",
    },
    {
        "category": "BSOD",
        "subcategory": "Power",
        "error_code": "Event ID 41",
        "error_pattern": r"(?i)(kernel.power.*41|event\s*id\s*41.*power|unexpected\s+shutdown)",
        "title": "Kernel-Power Event ID 41 (Unexpected Shutdown)",
        "description": "System rebooted without cleanly shutting down. The Kernel-Power 41 is logged.",
        "symptoms": "PC restarts randomly without BSOD. Event Viewer shows Kernel-Power 41 critical error.",
        "root_cause": "PSU failure, overheating, bad power cable, driver crash, or Windows update issue.",
        "remediation_steps": "1. Check CPU/GPU temperatures under load.\n2. Test with a known-good PSU.\n3. Update BIOS/UEFI firmware.\n4. Disable fast startup.\n5. Run 'powercfg /energy' for power diagnostics.\n6. Check Event Viewer for preceding errors.",
        "remediation_script": "fix_power_settings.ps1",
        "severity": "high",
        "confidence": 0.70,
        "tags": "power,shutdown,restart,kernel-power,psu",
    },
    {
        "category": "BSOD",
        "subcategory": "Watchdog",
        "error_code": "0x00000133",
        "error_pattern": r"(?i)(DPC_WATCHDOG_VIOLATION|0x00000133)",
        "title": "BSOD: DPC_WATCHDOG_VIOLATION",
        "description": "A Deferred Procedure Call ran longer than allowed.",
        "symptoms": "BSOD with STOP 0x133, common after driver or firmware updates.",
        "root_cause": "Outdated SSD firmware, storage controller driver, or incompatible driver.",
        "remediation_steps": "1. Update SSD firmware from manufacturer.\n2. Update SATA/NVMe controller driver.\n3. Run 'sfc /scannow'.\n4. Switch SATA mode in BIOS (AHCI vs IDE) if applicable.\n5. Update all drivers via Windows Update.",
        "remediation_script": "fix_bsod_general.ps1",
        "severity": "critical",
        "confidence": 0.80,
        "tags": "bsod,dpc,watchdog,ssd,storage",
    },

    # ============================================================
    # Service Failures — 8 entries
    # ============================================================
    {
        "category": "Service",
        "subcategory": "Windows Update",
        "error_code": "0x80070002",
        "error_pattern": r"(?i)(0x80070002|windows\s+update.*fail|update.*error.*0x80)",
        "title": "Windows Update Error 0x80070002",
        "description": "Windows Update fails with 'file not found' error.",
        "symptoms": "Updates fail to install. Error 0x80070002 in Windows Update or event log.",
        "root_cause": "Corrupted Windows Update cache, missing update components, or date/time mismatch.",
        "remediation_steps": "1. Run Windows Update Troubleshooter.\n2. Clear the SoftwareDistribution folder.\n3. Reset Windows Update components.\n4. Verify system date/time is correct.\n5. Run 'DISM /Online /Cleanup-Image /RestoreHealth'.",
        "remediation_script": "fix_windows_update.ps1",
        "severity": "medium",
        "confidence": 0.88,
        "tags": "update,windows update,0x80070002",
    },
    {
        "category": "Service",
        "subcategory": "Windows Update",
        "error_code": "0x800F081F",
        "error_pattern": r"(?i)(0x800F081F|\.NET\s*Framework.*install.*fail|DISM.*source\s+files\s+could\s+not\s+be\s+found)",
        "title": "DISM/Feature Install Error 0x800F081F",
        "description": ".NET Framework or Windows feature installation fails — source files not found.",
        "symptoms": "Cannot enable Windows features or install .NET 3.5. DISM returns 0x800F081F.",
        "root_cause": "Windows component store corruption or missing source in WinSxS folder.",
        "remediation_steps": "1. Run 'DISM /Online /Cleanup-Image /RestoreHealth'.\n2. Try install with Windows ISO: DISM /Online /Enable-Feature /FeatureName:NetFx3 /Source:D:\\sources\\sxs /LimitAccess.\n3. Reset Windows Update components.\n4. Check Group Policy for 'Specify settings for optional component installation'.",
        "remediation_script": "fix_windows_update.ps1",
        "severity": "medium",
        "confidence": 0.85,
        "tags": "dism,dotnet,.net,feature,install",
    },
    {
        "category": "Service",
        "subcategory": "Print Spooler",
        "error_code": "Event ID 7031",
        "error_pattern": r"(?i)(print\s*spooler.*stop|spooler.*crash|event.*7031.*spooler|cannot\s+print)",
        "title": "Print Spooler Service Crash",
        "description": "The Print Spooler service stops unexpectedly, preventing printing.",
        "symptoms": "Users cannot print. Print Spooler service shows as stopped. Event ID 7031 in System log.",
        "root_cause": "Corrupted print job, bad printer driver, or corrupted spool files.",
        "remediation_steps": "1. Clear the print queue: stop Spooler, delete files in C:\\Windows\\System32\\spool\\PRINTERS\\, start Spooler.\n2. Remove and re-add the printer.\n3. Update printer driver.\n4. Run printer troubleshooter.\n5. Check for conflicting printer software.",
        "remediation_script": "fix_print_spooler.ps1",
        "severity": "medium",
        "confidence": 0.90,
        "tags": "printer,spooler,print,service",
    },
    {
        "category": "Service",
        "subcategory": "DNS Client",
        "error_code": "Event ID 1014",
        "error_pattern": r"(?i)(dns.*timeout|name\s+resolution.*fail|event.*1014.*dns|cannot\s+resolve)",
        "title": "DNS Resolution Failure (Event ID 1014)",
        "description": "DNS Client cannot resolve hostnames, causing connectivity issues.",
        "symptoms": "Websites unreachable by name but reachable by IP. Event ID 1014 in System log.",
        "root_cause": "DNS server unreachable, misconfigured DNS settings, DNS cache corruption.",
        "remediation_steps": "1. Flush DNS: 'ipconfig /flushdns'.\n2. Verify DNS settings (ipconfig /all).\n3. Test with alternate DNS (8.8.8.8).\n4. Restart DNS Client service.\n5. Run 'netsh winsock reset'.",
        "remediation_script": "fix_network_reset.ps1",
        "severity": "high",
        "confidence": 0.88,
        "tags": "dns,resolution,network,connectivity",
    },
    {
        "category": "Service",
        "subcategory": "RPC",
        "error_code": "1722",
        "error_pattern": r"(?i)(rpc\s+server\s+is\s+unavailable|error\s+1722|0x800706BA)",
        "title": "RPC Server Unavailable (Error 1722)",
        "description": "RPC service is unavailable, blocking remote management and AD operations.",
        "symptoms": "Cannot connect to remote machines, Group Policy fails, AD replication errors.",
        "root_cause": "RPC service stopped, firewall blocking ports 135/445, network issues.",
        "remediation_steps": "1. Verify RPC service is running.\n2. Check Windows Firewall rules for RPC (TCP 135, dynamic ports).\n3. Test network connectivity (ping, telnet port 135).\n4. Restart Remote Procedure Call service.\n5. Check for time sync issues between machines.",
        "remediation_script": "fix_services_restart.ps1",
        "severity": "high",
        "confidence": 0.85,
        "tags": "rpc,remote,service,firewall,active directory",
    },
    {
        "category": "Service",
        "subcategory": "WMI",
        "error_code": "0x80041003",
        "error_pattern": r"(?i)(wmi.*access\s+denied|0x80041003|wmi.*repository.*corrupt|wbem)",
        "title": "WMI Repository Corruption / Access Denied",
        "description": "WMI queries fail due to corrupted repository or permissions.",
        "symptoms": "SCCM/SCOM agents fail, scripts using WMI return errors, management tools broken.",
        "root_cause": "Corrupted WMI repository, permission issues, or broken WMI providers.",
        "remediation_steps": "1. Run 'winmgmt /verifyrepository'.\n2. If inconsistent: 'winmgmt /salvagerepository'.\n3. If still broken: 'winmgmt /resetrepository'.\n4. Re-register WMI DLLs.\n5. Restart Windows Management Instrumentation service.",
        "remediation_script": "fix_wmi_repair.ps1",
        "severity": "high",
        "confidence": 0.82,
        "tags": "wmi,repository,sccm,management",
    },
    {
        "category": "Service",
        "subcategory": "Task Scheduler",
        "error_code": "0x80070005",
        "error_pattern": r"(?i)(task\s+scheduler.*access\s+denied|scheduled\s+task.*fail|0x80070005.*task)",
        "title": "Scheduled Task Access Denied",
        "description": "Scheduled tasks fail with Access Denied error.",
        "symptoms": "Tasks show 'Last Run Result: 0x80070005'. Scheduled jobs not executing.",
        "root_cause": "Service account password changed, incorrect 'Log on as batch job' right, or UAC.",
        "remediation_steps": "1. Update the task's credentials (Run As account).\n2. Grant 'Log on as a batch job' in Local Security Policy.\n3. Check 'Run with highest privileges' if needed.\n4. Verify the account is not locked.\n5. Test running the task manually.",
        "remediation_script": None,
        "severity": "medium",
        "confidence": 0.85,
        "tags": "task scheduler,access denied,permissions,batch job",
    },
    {
        "category": "Service",
        "subcategory": "Windows Activation",
        "error_code": "0xC004F074",
        "error_pattern": r"(?i)(0xC004F074|activation.*fail|kms.*not\s+found|slui|license.*expir)",
        "title": "Windows Activation / KMS Error",
        "description": "Windows fails to activate against KMS server.",
        "symptoms": "Activation watermark on desktop, 'Windows is not activated' message, Event ID 12288.",
        "root_cause": "KMS server unreachable, DNS SRV record missing, firewall blocking port 1688.",
        "remediation_steps": "1. Verify KMS DNS SRV: 'nslookup -type=srv _vlmcs._tcp.domain.com'.\n2. Set KMS server manually: 'slmgr /skms kmsserver.domain.com'.\n3. Activate: 'slmgr /ato'.\n4. Check firewall for port 1688.\n5. Verify product key: 'slmgr /dlv'.",
        "remediation_script": None,
        "severity": "medium",
        "confidence": 0.80,
        "tags": "activation,kms,license,windows",
    },

    # ============================================================
    # Network — 7 entries
    # ============================================================
    {
        "category": "Network",
        "subcategory": "DHCP",
        "error_code": "APIPA 169.254.x.x",
        "error_pattern": r"(?i)(169\.254\.\d+\.\d+|apipa|dhcp.*fail|no\s+valid\s+ip|limited\s+connectivity)",
        "title": "DHCP Failure — APIPA Address Assigned",
        "description": "Machine receives a 169.254.x.x address instead of a valid DHCP lease.",
        "symptoms": "No network/internet. IP is 169.254.x.x. 'Limited connectivity' in network status.",
        "root_cause": "DHCP server unreachable, NIC disabled/faulty, network cable issue, DHCP scope exhausted.",
        "remediation_steps": "1. Run 'ipconfig /release' then 'ipconfig /renew'.\n2. Check physical cable/Wi-Fi connection.\n3. Restart DHCP Client service.\n4. Check DHCP server is running and has available leases.\n5. Run 'netsh winsock reset' and reboot.",
        "remediation_script": "fix_network_reset.ps1",
        "severity": "high",
        "confidence": 0.90,
        "tags": "dhcp,apipa,network,ip,connectivity",
    },
    {
        "category": "Network",
        "subcategory": "VPN",
        "error_code": "789",
        "error_pattern": r"(?i)(vpn.*error\s*789|l2tp.*fail|ipsec.*fail|vpn.*connect.*fail)",
        "title": "VPN L2TP/IPsec Connection Error 789",
        "description": "VPN connection fails with L2TP error 789.",
        "symptoms": "Cannot establish VPN. Error: 'The L2TP connection attempt failed because the security layer encountered a processing error'.",
        "root_cause": "IPsec service not running, registry key missing, NAT-T not configured, certificate issue.",
        "remediation_steps": "1. Set registry: HKLM\\SYSTEM\\CurrentControlSet\\Services\\PolicyAgent AssumeUDPEncapsulationContextOnSendRule=2.\n2. Restart IPsec Policy Agent and IKE services.\n3. Verify pre-shared key matches server.\n4. Check firewall allows UDP 500 and 4500.\n5. Reboot after registry change.",
        "remediation_script": "fix_vpn_l2tp.ps1",
        "severity": "high",
        "confidence": 0.82,
        "tags": "vpn,l2tp,ipsec,remote access",
    },
    {
        "category": "Network",
        "subcategory": "Wi-Fi",
        "error_code": "WLAN AutoConfig",
        "error_pattern": r"(?i)(wifi.*disconnect|wireless.*drop|wlan.*autoconfig.*fail|wi-fi.*intermittent)",
        "title": "Wi-Fi Intermittent Disconnections",
        "description": "Wireless connection drops intermittently.",
        "symptoms": "Wi-Fi disconnects randomly, reconnects after a few seconds, or fails to reconnect.",
        "root_cause": "Power management turning off adapter, driver bug, channel congestion, or router issue.",
        "remediation_steps": "1. Disable power management: Device Manager → Wi-Fi adapter → Power Management → uncheck 'Allow the computer to turn off this device'.\n2. Update wireless driver.\n3. Forget and reconnect to the network.\n4. Change Wi-Fi channel on router.\n5. Run network troubleshooter.",
        "remediation_script": "fix_wifi_power.ps1",
        "severity": "medium",
        "confidence": 0.78,
        "tags": "wifi,wireless,disconnect,power management",
    },
    {
        "category": "Network",
        "subcategory": "SMB",
        "error_code": "0x80004005",
        "error_pattern": r"(?i)(cannot\s+access.*\\\\|network\s+path.*not\s+found|smb.*fail|0x80004005.*share|file\s+share.*error)",
        "title": "Network Share / SMB Access Failure",
        "description": "Cannot access network file shares (SMB/CIFS).",
        "symptoms": "Error accessing \\\\server\\share. 'Network path not found' or 'Access denied'.",
        "root_cause": "SMBv1 disabled, incorrect credentials cached, firewall blocking 445, DNS issue.",
        "remediation_steps": "1. Test: 'net use \\\\server\\share /user:domain\\user'.\n2. Clear cached credentials: 'net use * /delete'.\n3. Check SMB version: 'Get-SmbConnection'.\n4. Verify firewall allows TCP 445.\n5. Check DNS resolution of the server.\n6. Enable SMBv2/v3 if only v1 was in use.",
        "remediation_script": "fix_network_reset.ps1",
        "severity": "medium",
        "confidence": 0.82,
        "tags": "smb,file share,network,cifs,share",
    },
    {
        "category": "Network",
        "subcategory": "Proxy",
        "error_code": "ERR_PROXY_CONNECTION_FAILED",
        "error_pattern": r"(?i)(proxy.*fail|err_proxy|pac.*error|proxy\s+settings|unable.*proxy)",
        "title": "Proxy Configuration / Connection Failure",
        "description": "Proxy settings misconfigured preventing internet access.",
        "symptoms": "Browsers show proxy errors. Internet works with proxy disabled. WPAD issues.",
        "root_cause": "Incorrect proxy settings, PAC file unreachable, malware modifying proxy, GPO conflict.",
        "remediation_steps": "1. Check proxy: Settings → Network & Internet → Proxy.\n2. Verify PAC URL is reachable.\n3. Reset proxy: 'netsh winhttp reset proxy'.\n4. Check for malware modifying proxy settings.\n5. Verify Group Policy proxy settings.",
        "remediation_script": "fix_network_reset.ps1",
        "severity": "medium",
        "confidence": 0.80,
        "tags": "proxy,internet,pac,wpad,browser",
    },
    {
        "category": "Network",
        "subcategory": "Firewall",
        "error_code": "MpsSvc",
        "error_pattern": r"(?i)(windows\s+firewall.*not\s+start|mpssvc.*fail|firewall.*broken|base\s+filtering\s+engine)",
        "title": "Windows Firewall Service Failure",
        "description": "Windows Firewall/Defender Firewall service fails to start.",
        "symptoms": "Firewall shows as off and won't turn on. MpsSvc service fails to start.",
        "root_cause": "Corrupted firewall policy, BFE (Base Filtering Engine) stopped, registry damage.",
        "remediation_steps": "1. Start Base Filtering Engine service first.\n2. Then start Windows Firewall (MpsSvc).\n3. Reset firewall: 'netsh advfirewall reset'.\n4. Re-register firewall DLLs.\n5. Run 'sfc /scannow' for system file repair.",
        "remediation_script": "fix_services_restart.ps1",
        "severity": "high",
        "confidence": 0.82,
        "tags": "firewall,mpssvc,bfe,security,service",
    },
    {
        "category": "Network",
        "subcategory": "NIC",
        "error_code": "Code 31",
        "error_pattern": r"(?i)(network\s+adapter.*not\s+working|code\s+31|nic.*fail|ethernet.*down|no\s+internet.*adapter)",
        "title": "Network Adapter Not Working (Code 31)",
        "description": "Network adapter shows error Code 31 in Device Manager.",
        "symptoms": "No network icon, adapter shows yellow exclamation in Device Manager, Code 31 error.",
        "root_cause": "Corrupted driver, registry entries, or hardware failure.",
        "remediation_steps": "1. Uninstall adapter in Device Manager and scan for hardware changes.\n2. Delete UpperFilters/LowerFilters in HKLM\\SYSTEM\\CurrentControlSet\\Control\\Class\\{4d36e972}.\n3. Install latest driver from manufacturer.\n4. Run 'netcfg -d' to reset network config.\n5. Test adapter in another machine if possible.",
        "remediation_script": "fix_network_reset.ps1",
        "severity": "high",
        "confidence": 0.75,
        "tags": "nic,adapter,code 31,driver,ethernet",
    },

    # ============================================================
    # Disk / Storage — 5 entries
    # ============================================================
    {
        "category": "Disk",
        "subcategory": "Space",
        "error_code": "Low Disk Space",
        "error_pattern": r"(?i)(low\s+disk\s+space|drive.*full|no\s+space|disk\s+space.*critical|C:.*100%)",
        "title": "Low Disk Space on System Drive",
        "description": "System drive running critically low on disk space.",
        "symptoms": "Low disk space warning, applications fail to save, Windows updates fail, system slowdown.",
        "root_cause": "Temp files, old updates, large log files, user data on C:, WinSxS bloat.",
        "remediation_steps": "1. Run Disk Cleanup (cleanmgr) with 'Clean up system files'.\n2. Clear temp folders.\n3. Run 'DISM /Online /Cleanup-Image /StartComponentCleanup'.\n4. Move user data to D: drive.\n5. Check for large files: 'Get-ChildItem C:\\ -Recurse | Sort Length -Desc | Select -First 20'.",
        "remediation_script": "fix_disk_cleanup.ps1",
        "severity": "high",
        "confidence": 0.92,
        "tags": "disk,space,storage,cleanup,temp",
    },
    {
        "category": "Disk",
        "subcategory": "SMART",
        "error_code": "Event ID 7",
        "error_pattern": r"(?i)(smart.*fail|disk.*bad\s+sector|event.*id.*7.*disk|reallocated\s+sector|pending\s+sector|i/o\s+error)",
        "title": "Disk SMART Failure / Bad Sectors",
        "description": "Hard drive reporting SMART errors or bad sectors.",
        "symptoms": "Slow file access, Event ID 7/51 in System log, SMART warnings, data corruption.",
        "root_cause": "Physical disk degradation, manufacturing defect, excessive wear.",
        "remediation_steps": "1. Back up data immediately.\n2. Run 'chkdsk /r' to map bad sectors.\n3. Check SMART: 'wmic diskdrive get status'.\n4. Plan disk replacement.\n5. Use manufacturer diagnostic tool (e.g. SeaTools, Samsung Magician).",
        "remediation_script": "fix_disk_check.ps1",
        "severity": "critical",
        "confidence": 0.90,
        "tags": "smart,disk,bad sector,hdd,ssd,hardware",
    },
    {
        "category": "Disk",
        "subcategory": "File System",
        "error_code": "NTFS",
        "error_pattern": r"(?i)(file\s+system.*corrupt|ntfs.*error|chkdsk.*required|dirty\s+bit|volume.*dirty)",
        "title": "NTFS File System Corruption",
        "description": "NTFS volume has corruption or dirty bit set.",
        "symptoms": "Chkdsk runs on every boot, file access errors, 'The volume is dirty' messages.",
        "root_cause": "Improper shutdown, power loss, failing disk, driver bug.",
        "remediation_steps": "1. Run 'chkdsk C: /f /r' (requires reboot for C:).\n2. Check dirty bit: 'fsutil dirty query C:'.\n3. Clear dirty bit after repair: 'fsutil dirty set C: 0' is not valid — chkdsk will clear it.\n4. If persistent, check disk hardware.\n5. Back up and consider reformatting if chkdsk keeps finding errors.",
        "remediation_script": "fix_disk_check.ps1",
        "severity": "high",
        "confidence": 0.85,
        "tags": "ntfs,filesystem,corrupt,chkdsk,dirty",
    },
    {
        "category": "Disk",
        "subcategory": "BitLocker",
        "error_code": "BitLocker Recovery",
        "error_pattern": r"(?i)(bitlocker.*recovery|recovery\s+key|bitlocker.*locked|tpm.*error.*bitlocker)",
        "title": "BitLocker Recovery Mode Triggered",
        "description": "System boots into BitLocker recovery, requiring recovery key.",
        "symptoms": "Blue BitLocker recovery screen on boot asking for 48-digit recovery key.",
        "root_cause": "BIOS/firmware update changed TPM state, hardware change detected, Secure Boot change.",
        "remediation_steps": "1. Enter recovery key from Azure AD or AD backup.\n2. Check: 'manage-bde -protectors C: -get' after recovery.\n3. Suspend BitLocker before BIOS updates: 'manage-bde -protectors C: -disable'.\n4. Re-enable after update: 'manage-bde -protectors C: -enable'.\n5. Backup recovery key to AD/Azure AD.",
        "remediation_script": None,
        "severity": "high",
        "confidence": 0.88,
        "tags": "bitlocker,encryption,recovery,tpm,boot",
    },
    {
        "category": "Disk",
        "subcategory": "USB",
        "error_code": "Code 43",
        "error_pattern": r"(?i)(usb.*not\s+recognized|code\s+43.*usb|unknown\s+usb\s+device|usb.*descriptor.*fail)",
        "title": "USB Device Not Recognized (Code 43)",
        "description": "USB device fails to initialize, showing Code 43 in Device Manager.",
        "symptoms": "USB device not working, Device Manager shows yellow exclamation with Code 43.",
        "root_cause": "Driver failure, USB hub power issue, faulty cable/port, device malfunction.",
        "remediation_steps": "1. Try different USB port (preferably directly on motherboard).\n2. Uninstall device in Device Manager and replug.\n3. Disable USB selective suspend in Power Options.\n4. Update USB host controller drivers.\n5. Try the device on another machine to rule out hardware failure.",
        "remediation_script": None,
        "severity": "medium",
        "confidence": 0.80,
        "tags": "usb,code 43,device,hardware,port",
    },

    # ============================================================
    # Active Directory — 5 entries
    # ============================================================
    {
        "category": "Active Directory",
        "subcategory": "Authentication",
        "error_code": "KDC_ERR_PREAUTH_FAILED",
        "error_pattern": r"(?i)(account\s+locked|lockout|kdc.*preauth.*fail|event.*4740|too\s+many.*login\s+attempt)",
        "title": "Account Lockout (Event ID 4740)",
        "description": "User account gets locked out repeatedly.",
        "symptoms": "User cannot log in, account shows as locked in AD, Event ID 4740 in Security log.",
        "root_cause": "Wrong cached credentials, mapped drive with old password, service using old credentials, mobile device.",
        "remediation_steps": "1. Unlock account in Active Directory.\n2. Find lockout source: use Account Lockout Tools (LockoutStatus.exe).\n3. Check Event ID 4625 on the source machine.\n4. Clear cached credentials: Credential Manager → Windows Credentials → remove old entries.\n5. Check scheduled tasks and services running under the account.\n6. Disconnect mapped drives and reconnect with current password.",
        "remediation_script": None,
        "severity": "medium",
        "confidence": 0.90,
        "tags": "lockout,active directory,authentication,kerberos,credentials",
    },
    {
        "category": "Active Directory",
        "subcategory": "Replication",
        "error_code": "8453",
        "error_pattern": r"(?i)(ad\s+replication.*fail|replication.*error|dcdiag.*fail|event.*1864|error\s+8453)",
        "title": "Active Directory Replication Failure",
        "description": "Domain controller replication is failing.",
        "symptoms": "AD changes not propagating, dcdiag reports replication errors, Event ID 1864.",
        "root_cause": "Network connectivity between DCs, time sync off by >5 min, lingering objects, USN rollback.",
        "remediation_steps": "1. Run 'dcdiag /v' to identify failures.\n2. Run 'repadmin /showrepl' to check replication status.\n3. Verify time sync: 'w32tm /query /status'.\n4. Force replication: 'repadmin /syncall /AdeP'.\n5. Check DNS resolution between DCs.\n6. Remove lingering objects if detected.",
        "remediation_script": None,
        "severity": "critical",
        "confidence": 0.80,
        "tags": "active directory,replication,domain controller,dcdiag",
    },
    {
        "category": "Active Directory",
        "subcategory": "Group Policy",
        "error_code": "Event ID 1058",
        "error_pattern": r"(?i)(group\s+policy.*fail|gpo.*not\s+appl|gpupdate.*fail|event.*1058|rsop.*error)",
        "title": "Group Policy Processing Failure",
        "description": "Group Policy Objects not applying to machines or users.",
        "symptoms": "Settings not applying, gpresult shows errors, Event ID 1058/1030 in Application log.",
        "root_cause": "SYSVOL not accessible, GPO permissions wrong, network issues, WMI filter failing.",
        "remediation_steps": "1. Run 'gpupdate /force'.\n2. Check SYSVOL access: 'dir \\\\domain.com\\SYSVOL'.\n3. Run 'gpresult /r' to check applied/denied GPOs.\n4. Verify DNS and DC connectivity.\n5. Check GPO permissions in GPMC.\n6. Reset SYSVOL replication if needed.",
        "remediation_script": None,
        "severity": "high",
        "confidence": 0.82,
        "tags": "group policy,gpo,sysvol,domain,gpupdate",
    },
    {
        "category": "Active Directory",
        "subcategory": "Trust",
        "error_code": "ERROR_DOMAIN_TRUST_INCONSISTENT",
        "error_pattern": r"(?i)(trust\s+relationship.*fail|secure\s+channel.*broken|computer.*domain.*trust|nltest.*fail)",
        "title": "Domain Trust / Secure Channel Broken",
        "description": "Machine loses trust with the domain, cannot authenticate.",
        "symptoms": "'The trust relationship between this workstation and the primary domain failed' on login.",
        "root_cause": "Machine account password out of sync with AD, VM restored from old snapshot.",
        "remediation_steps": "1. Login with local admin account.\n2. Run PowerShell: 'Reset-ComputerMachinePassword -Server DomainController'.\n3. Or: Disjoin from domain, delete computer account in AD, rejoin domain.\n4. If VM, avoid reverting to snapshots older than 30 days.\n5. Reboot after fix.",
        "remediation_script": None,
        "severity": "high",
        "confidence": 0.92,
        "tags": "trust,domain,secure channel,computer account,authentication",
    },
    {
        "category": "Active Directory",
        "subcategory": "DNS",
        "error_code": "4013",
        "error_pattern": r"(?i)(ad\s+dns.*fail|srv\s+record.*missing|_ldap._tcp.*not\s+found|event.*4013|dclocator.*fail)",
        "title": "AD DNS SRV Records Missing",
        "description": "Active Directory DNS SRV records missing, preventing DC discovery.",
        "symptoms": "Clients cannot find domain controllers, login delays, Group Policy failures.",
        "root_cause": "DNS zone not AD-integrated, DC not registering records, DNS scavenging removed records.",
        "remediation_steps": "1. Check SRV records: 'nslookup -type=srv _ldap._tcp.dc._msdcs.domain.com'.\n2. Force re-registration: 'nltest /dsregdns'.\n3. Restart Netlogon service on DCs.\n4. Check DNS zone is AD-integrated.\n5. Verify 'Domain Controller' DNS registration GPO.",
        "remediation_script": None,
        "severity": "critical",
        "confidence": 0.85,
        "tags": "dns,active directory,srv,domain controller,ldap",
    },

    # ============================================================
    # Office / Microsoft 365 — 5 entries
    # ============================================================
    {
        "category": "Office",
        "subcategory": "Outlook",
        "error_code": "0x8004010F",
        "error_pattern": r"(?i)(outlook.*cannot\s+start|outlook.*profile.*corrupt|0x8004010F|ost.*corrupt|pst.*error)",
        "title": "Outlook Profile / OST Corruption",
        "description": "Outlook fails to start or load email due to profile or data file corruption.",
        "symptoms": "Outlook hangs on loading, 'Cannot start Microsoft Outlook', send/receive errors.",
        "root_cause": "Corrupted OST/PST file, damaged Outlook profile, add-in conflict.",
        "remediation_steps": "1. Start Outlook in Safe Mode: 'outlook.exe /safe'.\n2. Create new Outlook profile via Control Panel → Mail.\n3. Delete and recreate OST file.\n4. Run Inbox Repair Tool (ScanPST.exe).\n5. Disable COM add-ins one by one to find conflict.",
        "remediation_script": "fix_outlook_repair.ps1",
        "severity": "medium",
        "confidence": 0.88,
        "tags": "outlook,email,profile,ost,pst,office",
    },
    {
        "category": "Office",
        "subcategory": "Activation",
        "error_code": "0x4004F00C",
        "error_pattern": r"(?i)(office.*unlicensed|office.*activation.*fail|0x4004F00C|product\s+activation\s+required|subscription.*expir)",
        "title": "Microsoft Office Activation Failure",
        "description": "Office apps show 'Product Activation Required' or 'Unlicensed Product'.",
        "symptoms": "Red banner in Office apps, limited functionality, activation prompts.",
        "root_cause": "License expired, KMS/MAK key issue, cached license corrupted, token corrupted.",
        "remediation_steps": "1. Run 'cscript ospp.vbs /act' from Office install folder.\n2. Clear license cache: delete tokens in %localappdata%\\Microsoft\\Office\\Licenses.\n3. Reset Office activation: run Office Activation troubleshooter.\n4. Check KMS connectivity if using volume license.\n5. Re-enter product key if standalone.",
        "remediation_script": "fix_office_activation.ps1",
        "severity": "medium",
        "confidence": 0.85,
        "tags": "office,activation,license,365,subscription",
    },
    {
        "category": "Office",
        "subcategory": "Excel",
        "error_code": "Excel Not Responding",
        "error_pattern": r"(?i)(excel.*not\s+responding|excel.*crash|excel.*hang|spreadsheet.*slow|excel.*repair)",
        "title": "Excel Crashes or Not Responding",
        "description": "Excel hangs, crashes, or becomes unresponsive.",
        "symptoms": "Excel freezes when opening files, 'Not Responding' in title bar, frequent crashes.",
        "root_cause": "Corrupted file, add-in conflict, hardware acceleration issue, large data set.",
        "remediation_steps": "1. Start Excel in Safe Mode: 'excel.exe /safe'.\n2. Disable hardware acceleration: File → Options → Advanced → Display.\n3. Disable COM add-ins.\n4. Repair Office installation: Control Panel → Programs → Repair.\n5. Open file in 'Open and Repair' mode.",
        "remediation_script": None,
        "severity": "medium",
        "confidence": 0.82,
        "tags": "excel,crash,hang,office,spreadsheet",
    },
    {
        "category": "Office",
        "subcategory": "Teams",
        "error_code": "CAA20003",
        "error_pattern": r"(?i)(teams.*sign\s+in.*fail|teams.*caa\d+|teams.*cache|teams.*blank\s+screen|teams.*not\s+load)",
        "title": "Microsoft Teams Sign-in / Loading Failure",
        "description": "Teams fails to sign in or shows blank white screen.",
        "symptoms": "Teams stuck on loading screen, sign-in loop, error code CAA20003, blank window.",
        "root_cause": "Corrupted Teams cache, credential issue, proxy/firewall blocking, TLS config.",
        "remediation_steps": "1. Clear Teams cache: delete contents of %appdata%\\Microsoft\\Teams.\n2. Clear credentials from Windows Credential Manager.\n3. Ensure TLS 1.2 is enabled.\n4. Check proxy/firewall allows *.teams.microsoft.com and *.skype.com.\n5. Reinstall Teams if cache clear doesn't help.",
        "remediation_script": "fix_teams_cache.ps1",
        "severity": "medium",
        "confidence": 0.85,
        "tags": "teams,microsoft teams,sign in,cache,office 365",
    },
    {
        "category": "Office",
        "subcategory": "OneDrive",
        "error_code": "0x8004de40",
        "error_pattern": r"(?i)(onedrive.*sync.*fail|onedrive.*error|0x8004de40|onedrive.*not\s+sign|onedrive.*stuck)",
        "title": "OneDrive Sync Failure",
        "description": "OneDrive client fails to sync files or sign in.",
        "symptoms": "OneDrive icon shows error, files not syncing, sync paused, sign-in failure.",
        "root_cause": "TLS configuration, proxy blocking, corrupted cache, file path too long, account issue.",
        "remediation_steps": "1. Reset OneDrive: 'wsreset.exe' then '%localappdata%\\Microsoft\\OneDrive\\onedrive.exe /reset'.\n2. Check TLS 1.2 is enabled.\n3. Verify proxy settings allow *.sharepoint.com.\n4. Check file path lengths (max 400 chars).\n5. Unlink and re-link OneDrive account.",
        "remediation_script": None,
        "severity": "medium",
        "confidence": 0.80,
        "tags": "onedrive,sync,cloud,office 365,sharepoint",
    },

    # ============================================================
    # Hardware — 5 entries
    # ============================================================
    {
        "category": "Hardware",
        "subcategory": "RAM",
        "error_code": "MemoryDiagnostics-Results",
        "error_pattern": r"(?i)(memory.*diagnostic.*error|ram.*fail|memtest.*error|memory.*hardware\s+error|ecc.*error)",
        "title": "RAM Hardware Failure",
        "description": "Physical memory (RAM) is failing or has errors.",
        "symptoms": "Random crashes, BSODs (especially 0x50, 0x1A), application crashes, memory diagnostic errors.",
        "root_cause": "Faulty RAM module, overheating, incompatible RAM, motherboard memory slot issue.",
        "remediation_steps": "1. Run Windows Memory Diagnostic (mdsched.exe).\n2. Run MemTest86 for thorough testing.\n3. Test each DIMM individually.\n4. Reseat RAM modules.\n5. Check BIOS for memory settings (XMP profile).\n6. Replace faulty module.",
        "remediation_script": None,
        "severity": "critical",
        "confidence": 0.85,
        "tags": "ram,memory,hardware,dimm,bsod",
    },
    {
        "category": "Hardware",
        "subcategory": "CPU",
        "error_code": "WHEA Event ID 18",
        "error_pattern": r"(?i)(whea.*error|machine\s+check\s+exception|event.*18.*whea|cpu.*overheat|thermal\s+throttl)",
        "title": "CPU Hardware Error (WHEA / Machine Check)",
        "description": "CPU reporting hardware errors via WHEA (Windows Hardware Error Architecture).",
        "symptoms": "WHEA events in Event Viewer, thermal throttling, BSOD WHEA_UNCORRECTABLE_ERROR.",
        "root_cause": "CPU overheating, degraded thermal paste, failing CPU, motherboard VRM issue.",
        "remediation_steps": "1. Check CPU temperatures (HWMonitor, Core Temp).\n2. Clean CPU heatsink and fan.\n3. Replace thermal paste.\n4. Check CPU fan is spinning.\n5. Verify BIOS is not overclocking.\n6. Run CPU stress test (Prime95) while monitoring temps.",
        "remediation_script": None,
        "severity": "critical",
        "confidence": 0.80,
        "tags": "cpu,whea,thermal,overheat,hardware",
    },
    {
        "category": "Hardware",
        "subcategory": "GPU",
        "error_code": "Event ID 4101",
        "error_pattern": r"(?i)(display\s+driver.*crash|tdr.*fail|event.*4101|screen.*flicker|gpu.*error|nvlddmkm)",
        "title": "GPU / Display Driver Crash (TDR)",
        "description": "Display driver crashes and recovers (Timeout Detection and Recovery).",
        "symptoms": "Screen goes black briefly, 'Display driver stopped responding and has recovered', artifacts.",
        "root_cause": "Overheating GPU, driver bug, insufficient power, failing GPU, overclocking.",
        "remediation_steps": "1. Update GPU driver (clean install via DDU).\n2. Check GPU temperature under load.\n3. Increase TDR timeout in registry (TdrDelay).\n4. Ensure PSU provides adequate power.\n5. Disable GPU overclocking.\n6. Test with different GPU if available.",
        "remediation_script": None,
        "severity": "high",
        "confidence": 0.82,
        "tags": "gpu,display,tdr,driver,nvidia,amd,screen",
    },
    {
        "category": "Hardware",
        "subcategory": "Monitor",
        "error_code": "No Signal",
        "error_pattern": r"(?i)(no\s+signal|monitor.*black|display.*not\s+detect|external\s+monitor.*fail|hdmi.*not\s+working|second\s+screen)",
        "title": "Monitor / Display Not Detected",
        "description": "External or secondary monitor not detected or showing 'No Signal'.",
        "symptoms": "Monitor shows 'No Signal', not appearing in Display Settings, blank screen on external.",
        "root_cause": "Cable issue, wrong input source, driver not detecting, docking station problem.",
        "remediation_steps": "1. Check cable connections and try different cable.\n2. Verify correct input source on monitor.\n3. Press Win+P and select display mode.\n4. Update display driver.\n5. Try different port (HDMI/DP/VGA).\n6. If docking station: update dock firmware, try direct connection.",
        "remediation_script": None,
        "severity": "medium",
        "confidence": 0.78,
        "tags": "monitor,display,no signal,hdmi,docking station,screen",
    },
    {
        "category": "Hardware",
        "subcategory": "Audio",
        "error_code": "No Audio",
        "error_pattern": r"(?i)(no\s+sound|audio.*not\s+working|speaker.*fail|headphone.*no\s+audio|audio\s+service.*not\s+running)",
        "title": "No Audio Output",
        "description": "System produces no sound through any output device.",
        "symptoms": "No sound from speakers/headphones, audio icon shows X, audio service not responding.",
        "root_cause": "Audio driver issue, Windows Audio service stopped, wrong output device, hardware mute.",
        "remediation_steps": "1. Check volume and mute status.\n2. Verify correct output device in Sound Settings.\n3. Restart Windows Audio service.\n4. Update audio driver.\n5. Run audio troubleshooter.\n6. Check Device Manager for audio controller errors.",
        "remediation_script": "fix_audio_service.ps1",
        "severity": "medium",
        "confidence": 0.85,
        "tags": "audio,sound,speaker,headphone,driver",
    },

    # ============================================================
    # Driver — 4 entries
    # ============================================================
    {
        "category": "Driver",
        "subcategory": "Generic",
        "error_code": "Code 28",
        "error_pattern": r"(?i)(driver.*not\s+installed|code\s+28|no\s+driver.*found|device.*no\s+driver|unknown\s+device)",
        "title": "Device Driver Not Installed (Code 28)",
        "description": "Device has no driver installed and is non-functional.",
        "symptoms": "Yellow exclamation in Device Manager, 'Drivers for this device are not installed' (Code 28).",
        "root_cause": "Driver not included in Windows, driver missing after clean install, hardware too new/old.",
        "remediation_steps": "1. Right-click device → Update Driver → Search automatically.\n2. Identify device via Hardware ID (VEN/DEV).\n3. Download driver from manufacturer website.\n4. Run Windows Update for optional driver updates.\n5. Use vendor driver tool (e.g. Dell Command Update, Lenovo Vantage).",
        "remediation_script": None,
        "severity": "medium",
        "confidence": 0.88,
        "tags": "driver,code 28,device manager,install,hardware",
    },
    {
        "category": "Driver",
        "subcategory": "Compatibility",
        "error_code": "Code 52",
        "error_pattern": r"(?i)(driver.*signature.*fail|code\s+52|unsigned\s+driver|driver.*blocked|driver\s+signing)",
        "title": "Unsigned Driver Blocked (Code 52)",
        "description": "Windows blocks an unsigned driver from loading.",
        "symptoms": "Device not working, Code 52 in Device Manager, driver won't install.",
        "root_cause": "Driver not digitally signed, Secure Boot blocking unsigned drivers.",
        "remediation_steps": "1. Get signed driver from manufacturer.\n2. If must use unsigned: bcdedit /set nointegritychecks on (security risk).\n3. Temporarily disable Secure Boot in BIOS.\n4. Use 'pnputil /add-driver driver.inf' as admin.\n5. Contact vendor for signed driver release.",
        "remediation_script": None,
        "severity": "medium",
        "confidence": 0.80,
        "tags": "driver,unsigned,signature,secure boot,code 52",
    },
    {
        "category": "Driver",
        "subcategory": "Rollback",
        "error_code": "Post-Update Failure",
        "error_pattern": r"(?i)(driver\s+update.*broke|after\s+update.*not\s+work|roll\s*back\s+driver|device.*after\s+update)",
        "title": "Device Failure After Driver Update",
        "description": "Device stopped working after a driver update.",
        "symptoms": "Hardware worked before update, now shows errors or doesn't function. Recent Windows update.",
        "root_cause": "Incompatible new driver, Windows Update pushed a bad driver.",
        "remediation_steps": "1. Device Manager → device → Properties → Driver → Roll Back Driver.\n2. If rollback unavailable, uninstall device and reinstall old driver.\n3. Block automatic driver updates: 'wushowhide.diagcab' tool.\n4. Set Group Policy to prevent driver updates via Windows Update.\n5. Download known-good driver from manufacturer.",
        "remediation_script": None,
        "severity": "medium",
        "confidence": 0.85,
        "tags": "driver,update,rollback,windows update,compatibility",
    },
    {
        "category": "Driver",
        "subcategory": "Printer Driver",
        "error_code": "Printer Offline",
        "error_pattern": r"(?i)(printer.*offline|print.*driver.*error|cannot\s+install\s+printer|printer.*queue.*stuck|print.*fail)",
        "title": "Printer Offline / Driver Failure",
        "description": "Printer shows as offline or driver fails to install.",
        "symptoms": "Printer status 'Offline', print jobs stuck in queue, driver installation error.",
        "root_cause": "Driver incompatibility, spooler issue, network printer unreachable, port config wrong.",
        "remediation_steps": "1. Restart Print Spooler service.\n2. Set printer online: Printer Properties → uncheck 'Use Printer Offline'.\n3. Update/reinstall printer driver.\n4. Clear print queue.\n5. For network printers: verify IP address, ping printer.\n6. Remove and re-add printer with correct port.",
        "remediation_script": "fix_print_spooler.ps1",
        "severity": "medium",
        "confidence": 0.85,
        "tags": "printer,offline,driver,spooler,print queue",
    },

    # ============================================================
    # Security — 4 entries
    # ============================================================
    {
        "category": "Security",
        "subcategory": "Windows Defender",
        "error_code": "0x80070015",
        "error_pattern": r"(?i)(defender.*not\s+start|antivirus.*fail|malware.*detect|defender.*update.*fail|protection.*off)",
        "title": "Windows Defender / Antivirus Failure",
        "description": "Windows Defender fails to start, update, or scan.",
        "symptoms": "Defender shows as off, definitions outdated, scans fail, third-party AV conflict.",
        "root_cause": "Conflicting antivirus, corrupted Defender files, policy disabling Defender, service stopped.",
        "remediation_steps": "1. Uninstall third-party antivirus completely.\n2. Run 'sfc /scannow'.\n3. Reset Defender: remove HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\DisableAntiSpyware.\n4. Update definitions: 'MpCmdRun.exe -SignatureUpdate'.\n5. Restart Security Center service (wscsvc).",
        "remediation_script": "fix_defender_reset.ps1",
        "severity": "high",
        "confidence": 0.82,
        "tags": "defender,antivirus,security,malware,protection",
    },
    {
        "category": "Security",
        "subcategory": "Certificates",
        "error_code": "SEC_E_CERT_EXPIRED",
        "error_pattern": r"(?i)(certificate.*expir|ssl.*error|cert.*invalid|trust.*chain|certificate.*not\s+valid)",
        "title": "SSL/TLS Certificate Error",
        "description": "Certificate validation failures blocking secure connections.",
        "symptoms": "Browser certificate warnings, application SSL errors, internal site access failures.",
        "root_cause": "Expired certificate, missing root CA, clock skew, revoked certificate.",
        "remediation_steps": "1. Verify system date/time is correct.\n2. Check certificate expiry: 'certutil -verify cert.cer'.\n3. Install missing root/intermediate CA certificates.\n4. Update root certificate store: run Windows Update.\n5. Clear SSL state: Internet Options → Content → Clear SSL State.",
        "remediation_script": None,
        "severity": "high",
        "confidence": 0.85,
        "tags": "certificate,ssl,tls,expired,trust,security",
    },
    {
        "category": "Security",
        "subcategory": "UAC",
        "error_code": "0x80004005",
        "error_pattern": r"(?i)(access\s+denied|elevat.*fail|uac.*block|run\s+as\s+admin.*fail|permission.*denied.*admin)",
        "title": "UAC / Elevation Failure",
        "description": "User cannot elevate or run as admin, access denied errors.",
        "symptoms": "Admin programs won't launch, UAC prompt doesn't appear, 'Access Denied' on system operations.",
        "root_cause": "UAC policy, corrupted admin group membership, Local Security Policy restriction.",
        "remediation_steps": "1. Check UAC settings: Control Panel → User Accounts → Change UAC settings.\n2. Verify user is in local Administrators group: 'net localgroup administrators'.\n3. Check Local Security Policy → User Rights Assignment.\n4. Reset UAC: set EnableLUA=1 in HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System.\n5. Rebuild admin approval mode if broken.",
        "remediation_script": None,
        "severity": "high",
        "confidence": 0.78,
        "tags": "uac,admin,elevation,access denied,permissions",
    },
    {
        "category": "Security",
        "subcategory": "Ransomware",
        "error_code": "Encrypted Files",
        "error_pattern": r"(?i)(files?\s+encrypt|ransom|\.locked|decrypt.*files|cannot\s+open.*encrypt|unusual\s+file\s+extension)",
        "title": "Suspected Ransomware / File Encryption",
        "description": "Files appear encrypted with unusual extensions, possible ransomware infection.",
        "symptoms": "Files renamed with strange extensions (.locked, .crypto), ransom note on desktop, cannot open files.",
        "root_cause": "Ransomware infection via phishing email, exploit kit, RDP brute force.",
        "remediation_steps": "1. IMMEDIATELY isolate machine from network (disconnect cable/Wi-Fi).\n2. DO NOT pay the ransom.\n3. Identify ransomware variant: upload sample to id-ransomware.malwarehunterteam.com.\n4. Check nomoreransom.org for decryption tools.\n5. Restore from backup if available.\n6. Report to security team for full incident response.\n7. Scan all connected systems.",
        "remediation_script": None,
        "severity": "critical",
        "confidence": 0.75,
        "tags": "ransomware,encryption,malware,security incident,backup",
    },

    # ============================================================
    # Performance — 4 entries
    # ============================================================
    {
        "category": "Performance",
        "subcategory": "CPU",
        "error_code": "High CPU",
        "error_pattern": r"(?i)(high\s+cpu|cpu.*100%|system.*slow|process.*consuming|svchost.*high\s+cpu)",
        "title": "High CPU Usage / System Slowdown",
        "description": "CPU usage consistently high, causing system slowdown.",
        "symptoms": "System sluggish, fan running loud, Task Manager shows 100% CPU, specific process consuming CPU.",
        "root_cause": "Runaway process, Windows Update scanning, malware, driver issue, insufficient hardware.",
        "remediation_steps": "1. Open Task Manager → identify the high-CPU process.\n2. If svchost: use Resource Monitor to find the sub-service.\n3. If Windows Update: let it finish or restart the service.\n4. Scan for malware.\n5. Check for stuck WMI queries or SCCM scans.\n6. Update drivers, especially chipset drivers.",
        "remediation_script": "fix_performance_cpu.ps1",
        "severity": "medium",
        "confidence": 0.80,
        "tags": "cpu,performance,slow,svchost,task manager",
    },
    {
        "category": "Performance",
        "subcategory": "Memory",
        "error_code": "High Memory",
        "error_pattern": r"(?i)(high\s+memory|memory.*leak|out\s+of\s+memory|ram.*full|commit\s+charge.*high|pagefile.*full)",
        "title": "High Memory Usage / Memory Leak",
        "description": "System running out of available memory.",
        "symptoms": "System slow, 'Your computer is low on memory' warning, applications crashing, high commit charge.",
        "root_cause": "Memory leak in application/driver, too many applications, insufficient RAM, pagefile too small.",
        "remediation_steps": "1. Check Task Manager → Memory usage by process.\n2. Look for processes with growing memory over time (leak).\n3. Restart the leaking service/application.\n4. Increase pagefile size.\n5. Add more RAM if consistently maxed.\n6. Use RAMMap to analyze memory distribution.",
        "remediation_script": None,
        "severity": "medium",
        "confidence": 0.78,
        "tags": "memory,ram,leak,performance,pagefile",
    },
    {
        "category": "Performance",
        "subcategory": "Boot",
        "error_code": "Slow Boot",
        "error_pattern": r"(?i)(slow\s+boot|boot.*takes\s+long|startup.*slow|logon.*slow|windows.*slow\s+to\s+start)",
        "title": "Slow Boot / Startup Time",
        "description": "Windows takes an excessively long time to boot and reach the desktop.",
        "symptoms": "Boot takes >2 minutes, long time at 'Welcome' screen, desktop loads slowly.",
        "root_cause": "Too many startup programs, Group Policy processing, disk fragmentation, old HDD, failing drive.",
        "remediation_steps": "1. Disable unnecessary startup programs: Task Manager → Startup tab.\n2. Run 'msconfig' and review startup services.\n3. Enable Fast Startup: Power Options → 'Choose what the power buttons do'.\n4. Check disk health (HDD → consider SSD upgrade).\n5. Review Event Viewer boot logs for delays.\n6. Run 'xbootmgr -trace boot' for boot trace analysis.",
        "remediation_script": "fix_startup_optimize.ps1",
        "severity": "low",
        "confidence": 0.80,
        "tags": "boot,startup,slow,performance,startup programs",
    },
    {
        "category": "Performance",
        "subcategory": "Disk I/O",
        "error_code": "100% Disk",
        "error_pattern": r"(?i)(100%\s+disk|disk.*100\s*percent|disk\s+usage.*high|disk.*bottleneck|i/o.*slow|disk.*thrash)",
        "title": "100% Disk Usage",
        "description": "Disk usage stuck at 100% in Task Manager, causing extreme slowdown.",
        "symptoms": "System nearly frozen, Task Manager shows 100% disk, everything takes forever to load.",
        "root_cause": "Windows Search indexing, Superfetch/SysMain, Windows Update, failing HDD, antivirus scanning.",
        "remediation_steps": "1. Open Task Manager → identify process causing disk I/O.\n2. Disable SysMain service if on HDD.\n3. Disable Windows Search indexing temporarily.\n4. Check for Windows Update running in background.\n5. Check disk health (SMART).\n6. Strongly consider upgrading HDD to SSD.",
        "remediation_script": "fix_disk_usage.ps1",
        "severity": "high",
        "confidence": 0.85,
        "tags": "disk,100%,performance,ssd,hdd,sysmain,superfetch",
    },
]
